[build]
  command = "npm ci && npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_TAILWIND = "true"
  
[build.processing]
  skip_processing = false
  
[[plugins]]
  package = "@netlify/plugin-lighthouse"