# Netlify configuration file
[build]
  command = "yarn install && yarn build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18.19.0"
  SKIP_TAILWIND = "true"
  
[build.processing]
  skip_processing = false
  
[[plugins]]
  package = "@netlify/plugin-lighthouse"
